CREATE TABLE /*TABLE_PREFIX*/t_gdpr (
        fk_i_id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	g_user_id INT(10) UNSIGNED NOT NULL,
        b_gdpr TINYINT(1) NOT NULL DEFAULT 0,
	b_terms TINYINT(1) NOT NULL DEFAULT 0,
	b_privacy TINYINT(1) NOT NULL DEFAULT 0,
        b_custom TINYINT(1) NOT NULL DEFAULT 0,
	s_value LONGTEXT NULL,
        download_data LONGTEXT NULL,
	req_date DATETIME NULL,

        PRIMARY KEY (fk_i_id)
) ENGINE=InnoDB DEFAULT CHARACTER SET 'UTF8' COLLATE 'UTF8_GENERAL_CI';